In [1]:
import cv2

In [2]:
img_t = cv2.imread("smallgray.png",0)
img_t 

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [3]:
# slicing rows
img_t[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [4]:
# Slice to remain with 104, 121 and row below be 255, 255
img_t[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [5]:
# see shape of numpy array
img_t.shape

(3, 5)

In [6]:
# Using list conventions. Returns only columns from 2 - 3
img_t[:, 2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [7]:
img_t

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [11]:
# Parse axis. Returns num in col 4 on 2nd value
img_t[2,4]

97

In [12]:
img_t[2,3]

97

In [13]:
# Iterating through numpy array. Prints rows of numpy array
for i in img_t:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [14]:
# If you want to iterate through cols transpose(T)
for i in img_t.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [15]:
# If you want to iterate valuable value
for r in img_t.flat:
    print(r)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
